services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: DiscountDb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Attar@1982"
    ports:
      - "11433:1433"
    volumes:
    - sqlserverdata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_ERLANG_COOKIE=MY_SECRET_COOKIE
      # السطرين الجايين هما السر
      - RABBITMQ_NODENAME=rabbit@localhost
      - HOME=/var/lib/rabbitmq/mnesia # تغيير مسار الـ Home لمسار إحنا ضامنين صلاحياته
    ports:
      - "5672:5672"    # بورت البيانات (الذي تستخدمه الـ APIs حالياً)
      - "15672:15672"  # بورت لوحة التحكم (الذي تحاول فتحه)
    user: "0:0" 
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s # زودنا فترة السماح لـ 60 ثانية عشان ندي فرصة للويندوز يخلص الـ I/O بتاعه

  catalog-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: Catalog.API
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  discount-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: Discount.API
    ports:
      - "8003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  discount-grpc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: Discount.Grpc
    ports:
      - "8004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  basket-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: Basket.API
    ports:
      - "8002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      discount-grpc:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  ordering-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: Ordering.API
    ports:
      - "8005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      sqlserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ApiGateway
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    depends_on:
      catalog-api:
        condition: service_started
      basket-api:
        condition: service_started
      ordering-api:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    user: "0:0"
    environment:
    - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
    - seq_data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  shopping-aggregator:
   build:
    context: .
    dockerfile: Dockerfile
    args:
      PROJECT: Shopping.Aggregator
   ports:
     - "8006:8080"
   depends_on:
    - catalog-api
    - basket-api

volumes:
  sqlserverdata:
  rabbitmq_data:
  seq_data:
  